name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # optional dev tools
          pip install pytest

      - name: Lint YAML (load detectors)
        run: |
          python - << 'PY'
          import yaml,sys
          with open('detectors.yaml','r',encoding='utf-8') as f:
              yaml.safe_load(f)
          print('detectors.yaml OK')
          PY

      - name: Python syntax check
        run: python -m py_compile es_pii_extract_update.py

      - name: Run unit tests
        run: pytest -q
